# Generated by Django 4.2.4 on 2023-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hello', models.DateField()),
                ('value', models.FloatField()),
                ('mean', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
