# Generated by Django 4.2.4 on 2023-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseriesapp', '0002_remove_timeseriesdata_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesdata',
            name='timestamp',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
