# Generated by Django 4.2.4 on 2023-08-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseriesapp', '0004_alter_timeseriesdata_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseriesdata',
            old_name='mean',
            new_name='feature_1',
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='feature_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
