# Generated by Django 4.2.4 on 2023-08-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeseriesapp', '0006_remove_timeseriesdata_feature_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseriesdata',
            old_name='feature_1',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='value',
        ),
    ]
